#use a unix env
FROM centos:7.3.1611

RUN yum install -y perl
RUN yum install -y bzip2-devel
RUN yum install -y gcc gcc-c++ make zlib-devel xz-devel git
RUN ln -s `find /usr/lib64/ -type f -name "libbz2.so.1*"` /usr/lib64/libbz2.so.1.0

#Copy code into container
COPY ./easyJanus/ /app
WORKDIR /app/bedtools2
RUN make 
COPY ./easyJanus/bedtools2/bin/ /usr/bin/

#Set working dir
WORKDIR /app

#Define the command to run code
ENV PATH="/app:${PATH}"
ENV PATH="/app/bedtools:${PATH}"
ENV INP="/app/"
ENV OUT="/app/output/"

CMD ["/app/easyJanus_design.sh"]
